TARGET = average 2022_7_6_C2 celsius2fahr fahr2celsius fahr2celsius2 fahr2celsius3 fahr2celsius4 test triangle

all : $(TARGET)
average : $@
2022_7_6_C2 : $@
celsius2fahr : $@
fahr2celsius : $@
fahr2celsius2 : $@
fahr2celsius3 : $@
fahr2celsius4 : $@
test : $@
triangle : $@

clean :
	rm ${TARGET}
