main : average 2022_7_6_C2 celsius2fahr fahr2celsius fahr2celsius2 fahr2celsius3 fahr2celsius4 test triangle
average : average.o
2022_7_6_C2 : 2022_7_6_C2.o
celsius2fahr : celsius2fahr.o
fahr2celsius : fahr2celsius.o
fahr2celsius2 : fahr2celsius2.o
fahr2celsius3 : fahr2celsius3.o
fahr2celsius4 : fahr2celsius4.o
test : test.o
triangle : triangle.o

clean :
	rm 2022_7_6_C2.o 2022_7_6_C2 average.o average celsius2fahr.o celsius2fahr fahr2celsius.o fahr2celsius fahr2celsius2.o fahr2celsius2 fahr2celsius3.o fahr2celsius3 fahr2celsius4.o fahr2celsius4 test.o test triangle.o triangle
