TARGET = absoluteValue alphabet bigLetter bigLetter2 compare compare2 compare3 compare4 leafyear leafyear2 letterAttribute oddeven oddeven2 ordinaryyear passFail passFail2 posZeroNeg scoreGrade scoreGrade2 sizeof typecastaverage typecastfahr typecastmanwomanrate

main : $(TARGET)
absoluteValue : $@
alphabet : $@
bigLetter : $@
bigLetter2 : $@
compare : $@
compare2 : $@
compare3 : $@
compare4 : $@
leafyear : $@
leafyear2 : $@
letterAttribute : $@
oddeven : $@
oddeven2 : $@
ordinaryyear : $@
passFail : $@
passFail2 : $@
posZeroNeg : $@
scoreGrade : $@
scoreGrade2 : $@
sizeof : $@
typecastaverage : $@
typecastfahr : $@
typecastmanwomanrate : $@


clean:
	rm $(TARGET)