TARGET = arithmetics average2 circle fahrtocel genderRatio incrementor limits limits2 literal triangle2
CC = gcc
CFLAGS = -g -Wall

all : $(TARGET)
arithmetics : $@
average2 : $@
circle : $@
fahrtocel : $@
genderRatio : $@
incrementor : $@
limits : $@
limits2 : $@
literal : $@
triangle2 : $@

clean:
	rm $(TARGET)